// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3sTkaLJxiSqc-G04Hdhd9OYXmKC20zLs',
    appId: '1:365681482414:web:3335bb9790c6da89932b3f',
    messagingSenderId: '365681482414',
    projectId: 'ymmm-a757a',
    authDomain: 'ymmm-a757a.firebaseapp.com',
    storageBucket: 'ymmm-a757a.appspot.com',
    measurementId: 'G-BPEQR1G7VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANK0f7Oab8sHAf3nnWWtO8gPiPp0b3koA',
    appId: '1:365681482414:android:41d1f94132cee161932b3f',
    messagingSenderId: '365681482414',
    projectId: 'ymmm-a757a',
    storageBucket: 'ymmm-a757a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALXQ8PbZOCe5cH7Y0qyxJUP44fzGRVvMw',
    appId: '1:365681482414:ios:5ea66e2ca1e0c68f932b3f',
    messagingSenderId: '365681482414',
    projectId: 'ymmm-a757a',
    storageBucket: 'ymmm-a757a.appspot.com',
    iosBundleId: 'com.example.ymmmUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALXQ8PbZOCe5cH7Y0qyxJUP44fzGRVvMw',
    appId: '1:365681482414:ios:e0ab28f01e423d32932b3f',
    messagingSenderId: '365681482414',
    projectId: 'ymmm-a757a',
    storageBucket: 'ymmm-a757a.appspot.com',
    iosBundleId: 'com.example.ymmmUi.RunnerTests',
  );
}
