name: Build and deploy flutter web app

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Enable Flutter for the web
        run: flutter config --enable-web
      - name: Build Flutter web app
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Add files to Git
        run: |
          git --work-tree build/web add --all
      - name: Commit changes
        run: |
          git --work-tree build/web commit -m "Automatic deployment by github-actions"
      - name: Push changes to GitHub Pages
        run: |
          git --work-tree build/web push origin HEAD:gh-pages --force